remote_theme: pages-themes/minima@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Final Poject by BeiChen and YucenXie(Team31)
description: This is a final project about hotels booking demand.